export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';

export const FETCH_CATES_ICON_SETS_START = 'FETCH_CATES_ICON_SETS_START';
export const FETCH_CATES_ICON_SETS_PENDING = 'FETCH_CATES_ICON_SETS_PENDING';
export const FETCH_CATES_ICON_SETS_SUCCESS = 'FETCH_CATES_ICON_SETS_SUCCESS';
export const FETCH_CATES_ICON_SETS_FAIL = 'FETCH_CATES_ICON_SETS_FAIL';

export const DRAWER_TAB_CLICK = 'DRAWER_TAB_CLICK';
export const CURTAIN_RESUME_OVERLAY_CLICK = 'CURTAIN_RESUME_OVERLAY_CLICK';
export const CURTAIN_RESUME_INNER_ITEM_CLICK = 'CURTAIN_RESUME_INNER_ITEM_CLICK';
export const CURTAIN_RESUME_MAIN_CLICK = 'CURTAIN_RESUME_MAIN_CLICK';
export const CURTAIN_RESUME_FOOTER_CLICK = 'CURTAIN_RESUME_FOOTER_CLICK';