export const BACKGROUND_OPTION_WHITE = 'BACKGROUND_OPTION_WHITE';
export const BACKGROUND_OPTION_BLACK = 'BACKGROUND_OPTION_BLACK';
export const BACKGROUND_OPTION_TRANSPARENT = 'BACKGROUND_OPTION_TRANSPARENT';